### PR TITLE
DSD-1411: DS styles override for Vega

### PR DESCRIPTION
**Pull request by EdwinGuzman**
Resolves [DSD-1411](https://jira.nypl.org/browse/DSD-1497).

When adding the `Header` in Vega, we noticed that Vega related styles were affecting the `Header`.  Most of those styles were global styles. We can override those styles by setting the _same_ and existing styles we already use explicitly in DS elements. The `!important` flag was added and we can revisit those later.

@bigfishdesign13 I added an HTML font-size override that updated Vega's "62.5%" value to "1em". This doesn't affect Vega and also fixes the `Header` font size. So this is great!... but after what DXP reported, I'm worried about this. This may negatively affect Drupal 7, right? Should the script perhaps try to read the location of the Header and either set "1em" for Vega or "10px" for Drupal 7?

### CODE REVIEW

**Comment by EdwinGuzman** [comment]
Forgot to mention, this is live on QA Vega - https://nypltrain.na3.iiivega.com/.

I am essentially comparing what is on Vega with the prod Header instance. It's _not_ perfect but that last part I can't figure out. This is much better than how it appeared before.

**Review by bigfishdesign13 — COMMENTED** [review]
Every new CSS injection was added to fix something that was intriduced by Vega?  Overall, it looks good.  What is "the last part" you can't figure out?  I see there is some spacing shifts from one to the other, but I think that is acceptable for now.

Regarding the `1em` font size adjustmnet, I am not yet sure how that will impact the DXP site.

**Review by bigfishdesign13 — APPROVED** [review]
I meant to approve the PR.

**Comment by EdwinGuzman** [comment]
> Every new CSS injection was added to fix something that was intriduced by Vega?

Yes. I think of it as overriding a Vega style that was overriding an initial Header DS style.

> What is "the last part" you can't figure out? I see there is some spacing shifts from one to the other, but I think that is acceptable for now.

Yes, it was the shifting on the top nav but now that I take a closer look, it's actually not a problem. I was not paying attention to the scrollbar that shifted the page over. So this not a real problem.

**Pull request merged**
